language: android
jdk: oraclejdk8

env:
  global:
    - secure: FsHtQV3onZulOtXJjd+laUKEAX+vQwD+c86O6GEA7uBE0QCB5Q6tgFH7ffY/qFRDljhtSjlGn6vAnTdpWCiT2QgImYJrTSrBhh/Vtu2Ju0HxYyb8AwViUqyfcWBcPG7m9FgR6nhWYotojaCx1xlTdjf5x9ly3wSDXFO70ihdlnFzbzYA+85b3Mk+eRhFr+0EadAbkF1ILHF8v66b+DW8CEyUyux1Oow7kyQOA8QCu0ooaJj2MRQxkqi+lHxqtmnuQQt/Sb0zsAXp1SPGNRCBJR2Di+RbHXSo+YQy7kNsWIVd1A5ZZNCpEu48Uoa8fBvdINRhgeNrdr8Hj+ZTMk+hoYmCzh/3RcWOthwqg90dF4tQYWS6EcreKzMzIMgXsFpsNi5ocSKlHLXukHev+CXBio5ZHpRgp/VsObgVFd6+nmqE881EUV/QDykS0Gt5KdIbFv8M5w3NO78KZR6eXGsTgk2jtf1Iei2W4Sx84GnY3dpKNOC19nbdr1L+nHffVdgRmOs14pqV4XckDkA0JaEiY3b1gYKSDAow4ABEJ2NefNMB8iiOMYNotHplcOxyxccNRYHTNVrwbfglFlJZbGogcDzvMkw6DOppz1JhrUY5/FMkdAi0gaQvqpOh1psrDnf/s8Sm3qrZZvZiC1sMjpp0J9Y7rjcCGho66IVZhfBpCDs=
    - secure: Verook92/52vmWswN7dHkxEN0gOk4ntjTqimISTDRkpLpTylBgieN2kUgBdlstbjRGF2i6QUlIagDV79etyYZ9A47AWG4483VFtIjoa8QVxk+qmWM46UVXDnLURRe1nfTHDKIwKvAWZIMTPORJcFjH79RpBectGJ8slHlzs+4uhevRWPdXpjyoP3P+rAbNxFfNFWjQL4rpHoD4kSnrksJ0SKdAWVQWewE/Ru3Q3yx0hsOobtNA6FYkaNtXTcVY1baIXD3tSmjjhBIBqY/1Qw3nhfSZQG1c9aLtwRztLyRBAiLw/EyRNa/RufreITdQEyG56L5/YOyCiX6MVKu87FFRa0Pgju2kTnsAbFSyWrD6dil6dxddOyAHKEF7JHui0GZmi0S1mide3CZ98kcr9Hh2bExlVW4bYp6g8G2kDF5iis6/kwzyt3Zegr7DJ1h30GCphEmrptHjpZy8Csup6HaURMB7da+OCSSyiXZoapqeIiN36Gsh0vqUHymdgktd6a4kIsg8oIrnq9koa12I2PIlBvfCHA9oe4dRtKn/hWKW0IbQ7bTgCLrJ7vTtWVzECKHooAG1H90CW8hj0NoDDk54+2lofHA93+hRq1aQM3cwhEBphbLGXgzIRNDSY/vYimHkwZShhNxWvsZPpmoWBs2eJvjrzdEOebTYjqsrg+sro=
    - secure: j1Eqhw/BGDQu5j++DX4HJe1Ajd+mTB3Ex0eicGM/Z8rWq0YM1XaGJ51UO6N/uXy/47kvfzZ2jcfxk3ojL71zuepqBY41n5whbl/cK7GRXhAzmZXNQe0uWMKBIhXWWaNAK91gMzKs6sRsjllo8YMAVHFk/9WDoDVETLyKrhIyHjy3NiBte4/EwIu1cXbAOeNFvUw0ChptA5BFbPsALxCvZqTdvwTdKOMkoQNE4FLEq+LH7/ekMtkgfBaanBfWowtossQ/IA8JSXWgTeG3JEUQahQg9LSj62JqMd7kghOJifj3x2GXwDS+zu7my2GToAgXU7nGtwmoMlLMW7TQkA2EPZF7asEZXIea6xa/8wBenBrWW80EnHHBcrCIw5azmZw24DTaeQSCcYfFuQAH4Xj6+QkyiJXuFu9sXIzu4BzRUyrnfFA7l3NDlviRIbZVVnTxUuf3HGWMlowaws2hvYMmt/Z2KfbLwGFqIjvl9pJoL66q5gP/ey2UWnm42t79VxfiJ+Xcw5rHpQfSyEulLAo5pbkOqERmOc//aPoyBmXIe2IRnzu2vwdzNsjEP9oeIWpbpZTK95NXe5AosYMtUrQxJ58nP4HjiVzSvDAACSHlbWXiZnTPLPrpg0PUd6Gp+yCrIbjvPQP8hwC6Se8JUQaYbRfvm/fx1t3JsDpkOv/487g=
  android:
    components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - openssl aes-256-cbc -K $encrypted_768906361fb5_key -iv $encrypted_768906361fb5_iv -in keystore1.jks.enc -out keystore1.jks -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - chmod +x ./push-apk.sh
  - ./gradlew dependencies || true
script:
  - ./gradlew clean build
after_success:
  - ls
  - cp $TRAVIS_BUILD_DIR/keystore1.jks $HOME
  - cd app/build/outputs/apk/
  - ls
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore1.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk key1
  - jarsigner -verify app-release-unsigned.apk
  - ${ANDROID_HOME}/build-tools/26.0.0/zipalign -v 4 app-release-unsigned.apk qrmodule.apk
  - cp qrmodule.apk $HOME
  - cd $HOME
  - sh ./push-apk.sh
